[package]
name = "restaurant"
version = "0.1.0"
authors = ["Sean Tyler Myers <seamyers@amazon.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "restaurant"
path = "src/lib.rs"


[dependencies]

